# Render Blueprint - Deploy Frontend + Backend in one go
services:
  # Backend API Service
  - type: web
    name: mosdac-chatbot-api
    runtime: python
    plan: free
    buildCommand: |
      cd Backend
      chmod +x deploy.sh
      ./deploy.sh
    startCommand: |
      cd Backend
      gunicorn --bind 0.0.0.0:$PORT --timeout 120 chatbot_api:app
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDz_C5YEYgvPOhSdY6cLe2yZBLbGfkffao
      - key: NEO4J_URI
        value: neo4j+s://94588e50.databases.neo4j.io
      - key: NEO4J_USER
        value: hbhosale2004@gmail.com
      - key: NEO4J_PASSWORD
        value: Hbhosale@05
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT

  # Frontend React App
  - type: web
    name: mosdac-chatbot-frontend
    runtime: node
    plan: free
    buildCommand: |
      cd frontend2/celestial-conversations-nexus
      npm install
      npm run build
    startCommand: |
      cd frontend2/celestial-conversations-nexus
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: mosdac-chatbot-api
          property: host
