# Render deployment configuration
services:
  - type: web
    name: mosdac-chatbot-api
    runtime: python
    plan: free
    buildCommand: |
      cd Backend
      chmod +x deploy.sh
      ./deploy.sh
    startCommand: |
      cd Backend
      gunicorn --bind 0.0.0.0:$PORT --timeout 120 chatbot_api:app
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDz_C5YEYgvPOhSdY6cLe2yZBLbGfkffao
      - key: NEO4J_URI
        value: neo4j+s://94588e50.databases.neo4j.io
      - key: NEO4J_USER
        value: hbhosale2004@gmail.com
      - key: NEO4J_PASSWORD
        value: Hbhosale@05
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT
